<?php

return [
    'permissions_by_role' => [
        'super_admin' => [
            'super_admin.panel',
            'super_admin.features.gestionar',
            'super_admin.impersonation.controlada',
            'super_admin.integraciones.gestionar',
            'super_admin.seguridad.gestionar',
            'super_admin.auditoria.inmutable',
        ],
        'cliente' => [
            'catalogo.ver',
            'carrito.gestionar',
            'checkout.crear',
            'pedidos.ver_propios',
            'resenas.crear',
            'direcciones.gestionar',
        ],
        'vendedor' => [
            'vendedor.panel',
            'productos.gestionar_propios',
            'inventario.gestionar_propios',
            'pedidos.ver_recibidos',
            'fel.ver_propios',
            'comisiones.ver_propias',
            'ml.ver_predicciones_propias',
        ],
        'bodeguero' => [
            'bodeguero.panel',
            'inventario.ver_operativo',
            'inventario.ajustar_stock',
            'pedidos.preparar',
            'recepciones.registrar',
            'stock.reportar_incidencias',
        ],
        'proveedor' => [
            'proveedor.panel',
            'catalogo_mayorista.gestionar',
            'cotizaciones.gestionar',
            'abastecimiento.ver_solicitudes',
            'ordenes_compra.ver',
            'facturas_proveedor.gestionar',
        ],
        'soporte' => [
            'soporte.panel',
            'tickets.atender',
            'tickets_repartidor.atender',
            'tickets_repartidor.asignar',
            'clientes.asistir',
            'pedidos.seguimiento_soporte',
            'devoluciones.gestionar_soporte',
            'chatbot.supervisar',
        ],
        'contabilidad_finanzas' => [
            'contabilidad.panel',
            'pagos.conciliar',
            'transferencias.validar',
            'comisiones.liquidar',
            'repartidores.finanzas.conciliar',
            'repartidores.retiros.aprobar',
            'repartidores.cuentas_bancarias.validar',
            'reportes_financieros.ver',
            'facturacion.ver',
        ],
        'supervisor_logistica' => [
            'logistica.panel',
            'repartidores.supervisar',
            'rutas.planificar',
            'entregas.reasignar',
            'incidencias_logistica.gestionar',
            'zonas_entrega.supervisar',
        ],
        'admin' => [
            'admin.panel',
            'usuarios.gestionar',
            'roles.gestionar',
            'vendedores.aprobar',
            'vendedores.suspender',
            'categorias.gestionar',
            'productos.moderar',
            'pedidos.ver_todos',
            'pagos.ver_todos',
            'fel.ver_todos',
            'delivery_zones.gestionar',
            'ml.monitorear',
            'auditoria.ver',
            'configuracion.gestionar',
        ],
        'repartidor' => [
            'repartidor.panel',
            'entregas.ver_asignadas',
            'entregas.actualizar_estado',
            'tracking.enviar_ubicacion',
        ],
        'empleado' => [
            'empleado.panel',
            'transferencias.validar',
            'repartidores.finanzas.conciliar',
            'tickets_repartidor.atender',
            'contact_messages.atender',
            'resenas.moderar',
            'fraud_alerts.revisar',
        ],
    ],

    'catalog_permissions' => [
        'admin.panel',
        'auditoria.ver',
        'abastecimiento.ver_solicitudes',
        'bodeguero.panel',
        'carrito.crear',
        'carrito.gestionar',
        'catalogo.ver',
        'catalogo_mayorista.gestionar',
        'categorias.gestionar',
        'chatbot.supervisar',
        'checkout.crear',
        'clientes.asistir',
        'comisiones.liquidar',
        'comisiones.ver_propias',
        'configuracion.gestionar',
        'contact_messages.atender',
        'contabilidad.panel',
        'cotizaciones.gestionar',
        'devoluciones.gestionar_soporte',
        'delivery_zones.gestionar',
        'direcciones.gestionar',
        'empleado.panel',
        'entregas.actualizar_estado',
        'entregas.reasignar',
        'entregas.ver_asignadas',
        'facturas_proveedor.gestionar',
        'facturacion.ver',
        'fel.ver_propios',
        'fel.ver_todos',
        'fraud_alerts.revisar',
        'incidencias_logistica.gestionar',
        'inventario.ajustar_stock',
        'inventario.gestionar',
        'inventario.gestionar_propios',
        'inventario.ver_operativo',
        'logistica.panel',
        'ml.monitorear',
        'ml.ver_predicciones_propias',
        'ordenes.procesar',
        'ordenes.ver',
        'ordenes_compra.ver',
        'pagos.conciliar',
        'pagos.ver_todos',
        'pedidos.preparar',
        'pedidos.seguimiento_soporte',
        'pedidos.ver_propios',
        'pedidos.ver_recibidos',
        'pedidos.ver_todos',
        'productos.gestionar_propios',
        'productos.moderar',
        'proveedor.panel',
        'recepciones.registrar',
        'repartidor.panel',
        'repartidores.cuentas_bancarias.validar',
        'repartidores.finanzas.conciliar',
        'repartidores.retiros.aprobar',
        'repartidores.supervisar',
        'reportes_financieros.ver',
        'resenas.crear',
        'resenas.moderar',
        'roles.gestionar',
        'rutas.planificar',
        'sistema.configurar',
        'soporte.panel',
        'stock.reportar_incidencias',
        'super_admin.auditoria.inmutable',
        'super_admin.features.gestionar',
        'super_admin.impersonation.controlada',
        'super_admin.integraciones.gestionar',
        'super_admin.panel',
        'super_admin.seguridad.gestionar',
        'tickets.atender',
        'tickets_repartidor.asignar',
        'tickets_repartidor.atender',
        'tracking.enviar_ubicacion',
        'transferencias.validar',
        'usuarios.gestionar',
        'vendedor.panel',
        'vendedores.aprobar',
        'vendedores.suspender',
        'zonas_entrega.supervisar',
    ],

    'protected_roles' => [
        'super_admin',
        'admin',
        'cliente',
        'vendedor',
        'bodeguero',
        'proveedor',
        'soporte',
        'contabilidad_finanzas',
        'supervisor_logistica',
        'repartidor',
        'empleado',
    ],

    'restricted_permissions' => [
        'super_admin.panel' => ['super_admin'],
        'super_admin.features.gestionar' => ['super_admin'],
        'super_admin.impersonation.controlada' => ['super_admin'],
        'super_admin.integraciones.gestionar' => ['super_admin'],
        'super_admin.seguridad.gestionar' => ['super_admin'],
        'super_admin.auditoria.inmutable' => ['super_admin'],
        'roles.gestionar' => ['admin', 'super_admin'],
        'usuarios.gestionar' => ['admin', 'super_admin'],
        'configuracion.gestionar' => ['admin', 'super_admin'],
        'auditoria.ver' => ['admin', 'super_admin'],
        'repartidores.retiros.aprobar' => ['contabilidad_finanzas', 'super_admin'],
        'repartidores.cuentas_bancarias.validar' => ['contabilidad_finanzas', 'super_admin'],
        'entregas.reasignar' => ['supervisor_logistica', 'admin', 'super_admin'],
    ],
];
