global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: atlantia-nginx
    metrics_path: /health
    static_configs:
      - targets:
          - nginx:80

  - job_name: atlantia-ml-api
    metrics_path: /api/v1/health
    static_configs:
      - targets:
          - ml-api:8000

  - job_name: meilisearch
    metrics_path: /health
    static_configs:
      - targets:
          - meilisearch:7700
